User interface
noomdalv/Ruby_TicTacToe pull request #2
Opened 2019-09-25 18:11 UTC by lekegitrepo

### Milestone 2: User interface

2019-09-25 20:28 UTC, samgaco requested changes
#### Hi @lekegitrepo and @noomdalv :high_brightness: 

I Left some comments below and requested changes, all the comments are required, the comment tagged as a suggestion is just my own opinion and you could implement this requirement using any other approach.

**Things to work on:**

* Have into account, that each file should consist of only one class.
* game asks player to select from available moves
* game informs player if selected move is invalid
* The game should pic a winner or check if there was a draw
* game repeats all actions for next player's move

Please :pray: work on those and submit back for another code review once you are done.
-----------------
moving on :arrow_down: 
* **[For your next code review requests]**  Add a short summary of changes in Pull Request description


------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2019-09-25 20:28 UTC, samgaco commented on bin/main.rb
> +  p 'Player 1 Turn, please select your next move: '
* [**REQUIRED**] game asks player to select from available moves

what moves do we have available? the board doesn't show any reference for that, should they be numbers from 1 to 9? letters?

2019-09-25 20:28 UTC, samgaco commented on bin/main.rb
> +  p1turn = gets.chomp.to_i
* [**REQUIRED**] game informs player if selected move is invalid

what if I input: "**ojfiwfjwef**" , the game should not accept that input for a turn

2019-09-25 20:28 UTC, samgaco commented on bin/main.rb
> +  ending = p 'Thank you for playing Tic Tac Toe'
[**REQUIRED**] The game should pic a winner or check if there was a draw 


[**SUGGESTION**] of course is mocked, maybe the number 7 could be a win, and picking all the numbers except 7 could be a draw

2019-09-25 20:28 UTC, samgaco commented on bin/main.rb
> +  p 'Player 1 Turn, please select your next move: '
* [**REQUIRED**] game repeats all actions for next player's move

Think about how will you achieve the mockup to keep iterating until it finds a winner or the game is finally set as a draw. **hint**: a loop :D

2019-09-27 00:37 UTC, Ispirett approved these changes
Hey, @noomdalv @lekegitrepo really good job you can move on to the next milestone. :100:

2019-10-03 16:24 UTC, merged