Rspec tests
noomdalv/Ruby_TicTacToe pull request #5
Opened 2019-09-30 21:42 UTC by lekegitrepo

### Implement tests for all the methods

2019-10-01 01:20 UTC, Ispirett commented
Hey, guys, you need to use the correct git-flow please make a pull request that merges to the development branch.
resubmit for a review

2019-10-01 18:13 UTC, Oghenebrume50 commented
reviewing...........

2019-10-01 19:30 UTC, Oghenebrume50 requested changes
Hi Team, good job on the test, it works perfectly. :clap:  Let's add a few good practices to the test
Please make sure to have positive and negative test cases for tests. That is, if you test an outcome to be truthy then you should have a test for the false outcome too. 

and fix the merge conflict showing up also. 

Please submit a re-review when the changes are made

2019-10-02 18:25 UTC, samgaco approved these changes
Hi @lekegitrepo and @noomdalv :high_brightness: 

I see all the previous requirements implemented, the project is approved. You may merge to the master branch and submit the project completion form.

----------------
Please, remembet :arrow_down: 

* **[For your next code review requests]**  Add a short summary of changes in Pull Request description

-----------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-10-02 18:25 UTC, samgaco commented on spec/game_manager_spec.rb
> +      expect(game_manager.space_filled?(2)).to eq(false)
:+1:

2019-10-02 18:25 UTC, samgaco commented on spec/game_manager_spec.rb
> +			expect(game_manager.valid_move?(1)).to eq(true)
:white_check_mark:

2019-10-02 18:25 UTC, samgaco commented on spec/game_manager_spec.rb
> +      expect(game_manager.current_player).to eq('X')
:white_check_mark:

2019-10-02 18:25 UTC, samgaco commented on spec/game_manager_spec.rb
> +      expect(game_manager.full?).to eq(true)
:white_check_mark:

2019-10-03 16:21 UTC, merged